import { Injectable } from "@nestjs/common";
import { InjectModel } from "@nestjs/mongoose";
import { Model } from "mongoose";
import { v4 as uuidv4 } from "uuid";
import { Notification, NotificationRead } from "../../schemas";
import { CurrentUserPayload } from "../../common/decorators/current-user.decorator";

@Injectable()
export class NotificationsService {
  constructor(
    @InjectModel(Notification.name) private readonly notificationModel: Model<Notification>,
    @InjectModel(NotificationRead.name) private readonly notificationReadModel: Model<NotificationRead>,
  ) {}

  // ============================================================================
  // بنبني هنا كل الاستهدافات الممكنة لليوزر عشان مفيش إشعار يتفوت:
  // "all" (للكل) / "teachers" (كل المدرسين) / رقم الحلقة العادية / رقم المجموعة
  // التعليمية / "student:<id>" لطالب بعينه / "teacher:<username>" لمدرس بعينه.
  // ملحوظة: النسخة القديمة كانت ناسية تحط شرط المجموعة التعليمية (eduGroupId)
  // في استعلامات /me و /unread-count، فالمدرسين اللي بس بيدرّسوا مجموعة تعليمية
  // (وملهومش حلقة تحفيظ عادية) كانوا ممكن يفوتهم إشعارات — اتصلحت هنا.
  // ============================================================================
  private buildTargetFilter(user: CurrentUserPayload) {
    const or: any[] = [{ target: "all" }];
    if (user.role === "teacher") or.push({ target: "teachers" });
    if (user.groupId) or.push({ target: user.groupId });
    if (user.eduGroupId) or.push({ target: user.eduGroupId });
    if (user.role === "student" && user.studentId) or.push({ target: `student:${user.studentId}` });
    if (user.role === "teacher" && user.username) or.push({ target: `teacher:${user.username}` });
    return { $or: or };
  }

  async findAllForAdmin() {
    const notifications = await this.notificationModel.find().sort({ created_at: -1 }).lean();
    const readCounts = await this.notificationReadModel.aggregate([
      { $group: { _id: "$notification_id", count: { $sum: 1 } } },
    ]);
    const countMap = Object.fromEntries(readCounts.map((c) => [c._id, c.count]));
    return notifications.map((n) => ({ ...n, read_by_count: countMap[n.id] || 0 }));
  }

  async findMine(user: CurrentUserPayload) {
    const notifications = await this.notificationModel
      .find(this.buildTargetFilter(user))
      .sort({ created_at: -1 })
      .lean();
    const reads = await this.notificationReadModel.find({ username: user.username }).lean();
    const readSet = new Set(reads.map((r) => r.notification_id));
    return notifications.map((n) => ({ ...n, isRead: readSet.has(n.id) }));
  }

  async unreadCount(user: CurrentUserPayload) {
    const notifications = await this.notificationModel.find(this.buildTargetFilter(user)).lean();
    const reads = await this.notificationReadModel.find({ username: user.username }).lean();
    const readSet = new Set(reads.map((r) => r.notification_id));
    return { count: notifications.filter((n) => !readSet.has(n.id)).length };
  }

  async create(title: string, body: string, target: string, autoGenerated = false) {
    const id = uuidv4();
    await this.notificationModel.create({ id, title, body, target, auto_generated: autoGenerated });
    return { id, title, body, target };
  }

  // Helpers بتتنادى من موديولز تانية عشان تولّد إشعارات أوتوماتيك
  notifyAll(title: string, body: string) {
    return this.create(title, body, "all", true);
  }

  notifyTeachers(title: string, body: string) {
    return this.create(title, body, "teachers", true);
  }

  notifyGroup(groupId: string, title: string, body: string) {
    return this.create(title, body, groupId, true);
  }

  notifyStudent(studentId: string, title: string, body: string) {
    return this.create(title, body, `student:${studentId}`, true);
  }

  notifyTeacher(username: string, title: string, body: string) {
    return this.create(title, body, `teacher:${username}`, true);
  }

  async markRead(notificationId: string, username: string) {
    await this.notificationReadModel.findOneAndUpdate(
      { notification_id: notificationId, username },
      { notification_id: notificationId, username },
      { upsert: true },
    );
    return { message: "تم" };
  }

  async remove(id: string) {
    await this.notificationModel.deleteOne({ id });
    await this.notificationReadModel.deleteMany({ notification_id: id });
  }
}
